# Generated by Django 3.0.4 on 2020-04-14 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genreid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('iso_639_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('adult', models.BooleanField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('homepage', models.CharField(blank=True, max_length=1000, null=True)),
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_language', models.CharField(blank=True, max_length=2, null=True)),
                ('original_title', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('tagline', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('video', models.BooleanField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Productioncompanies',
            fields=[
                ('productioncompanyid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productioncompanies',
            },
        ),
        migrations.CreateModel(
            name='Productioncountries',
            fields=[
                ('iso_639_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productioncountries',
            },
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('birth_date', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesProductioncountries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Movies')),
                ('productioncountry_iso', models.ForeignKey(db_column='productioncountry_iso', on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Productioncountries')),
            ],
            options={
                'db_table': 'movies_productioncountries',
            },
        ),
        migrations.CreateModel(
            name='MoviesProductioncompanies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Movies')),
                ('productioncompanies', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Productioncompanies')),
            ],
            options={
                'db_table': 'movies_productioncompanies',
            },
        ),
        migrations.CreateModel(
            name='MoviesLanguages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Languages')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Movies')),
            ],
            options={
                'db_table': 'movies_languages',
            },
        ),
        migrations.CreateModel(
            name='MoviesGenres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Genres')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Movies')),
            ],
            options={
                'db_table': 'movies_genres',
            },
        ),
        migrations.CreateModel(
            name='MovieRatings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('movieid', models.ForeignKey(blank=True, db_column='movieid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Movies')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie_ratings',
            },
        ),
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.CharField(max_length=200)),
                ('credit_id', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('profile_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.Movies')),
            ],
            options={
                'db_table': 'casts',
            },
        ),
    ]
