# Generated by Django 3.0.4 on 2020-03-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('adult', models.BooleanField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('homepage', models.CharField(blank=True, max_length=1000, null=True)),
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_language', models.CharField(max_length=5)),
                ('original_title', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField()),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('tagline', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('video', models.BooleanField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
