# Generated by Django 3.0.4 on 2020-04-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
    ]
