# Generated by Django 3.0.4 on 2020-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20200401_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='movies',
            table=None,
        ),
    ]
